name: RPG
on: 
  push:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  auditexample:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm audit
      - run: npm outdated
      - run: npm test
      - run: npm run lint
