name: RPG
on: 
  push:

jobs:
  rpgts:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '1.27.1'
      - name: Cache https://
        uses: actions/cache@v2
        with:
          path: ~/.cache/deno/deps/https
          key: deno-https/v1-${{ github.sha }}
          restore-keys: deno-https/v1-
      - run: deno task lint
      - run: deno task coverage
