name: RPG
on: 
  push:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  rpgts:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 'v1.1.15'
      - run: deno lint --unstable
      - run: deno test
